In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import warnings
from __future__ import division

%matplotlib inline

In [2]:
dtype_dict = {'bathrooms':float, 
              'waterfront':int, 
              'sqft_above':int, 
              'sqft_living15':float, 
              'grade':int, 
              'yr_renovated':int, 
              'price':float, 
              'bedrooms':float, 
              'zipcode':str, 'long':float, 
              'sqft_lot15':float, 
              'sqft_living':float, 
              'floors':float, 
              'condition':int, 
              'lat':float, 'date':str, 
              'sqft_basement':int, 
              'yr_built':int, 
              'id':str, 
              'sqft_lot':int, 
              'view':int}

In [3]:
# Read the data
data_train = pd.read_csv("./data/kc_house_train_data.csv", dtype=dtype_dict)
data_test = pd.read_csv("./data/kc_house_test_data.csv", dtype=dtype_dict)

# Take a quick look at the data

In [4]:
data_train.head(n=3)

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0       3.0       1.00       1180.0   
1  6414100192  20141209T000000  538000.0       3.0       2.25       2570.0   
2  5631500400  20150225T000000  180000.0       2.0       1.00        770.0   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   

   sqft_living15  sqft_lot15  
0         1340.0      5650.0  
1         1690.0      7639.0  
2         2720.0      8062.0  

[3 rows x 21 columns]

In [5]:
data_train.describe()

price      bedrooms     bathrooms   sqft_living      sqft_lot  \
count  1.738400e+04  17384.000000  17384.000000  17384.000000  1.738400e+04   
mean   5.393666e+05      3.369363      2.115048   2080.029510  1.509191e+04   
std    3.696912e+05      0.906468      0.771783    921.630888  4.145929e+04   
min    7.500000e+04      0.000000      0.000000    290.000000  5.200000e+02   
25%    3.200000e+05      3.000000      1.750000   1420.000000  5.049500e+03   
50%    4.500000e+05      3.000000      2.250000   1910.000000  7.616000e+03   
75%    6.400000e+05      4.000000      2.500000   2550.000000  1.066525e+04   
max    7.700000e+06     10.000000      8.000000  13540.000000  1.651359e+06   

             floors    waterfront          view     condition         grade  \
count  17384.000000  17384.000000  17384.000000  17384.000000  17384.000000   
mean       1.494248      0.007651      0.236079      3.410780      7.655028   
std        0.539443      0.087141      0.767977      0.649828      1.169817   
min        1.000000      0.000000      0.000000      1.000000      1.000000   
25%        1.000000      0.000000      0.000000      3.000000      7.000000   
50%        1.500000      0.000000      0.000000      3.000000      7.000000   
75%        2.000000      0.000000      0.000000      4.000000      8.000000   
max        3.500000      1.000000      4.000000      5.000000     13.000000   

         sqft_above  sqft_basement      yr_built  yr_renovated           lat  \
count  17384.000000   17384.000000  17384.000000  17384.000000  17384.000000   
mean    1787.844512     292.184998   1971.152727     83.107973     47.559313   
std      827.108459     444.371429     29.328821    398.698029      0.138703   
min      290.000000       0.000000   1900.000000      0.000000     47.159300   
25%     1200.000000       0.000000   1952.000000      0.000000     47.468650   
50%     1560.000000       0.000000   1975.000000      0.000000     47.571400   
75%     2210.000000     560.000000   1997.000000      0.000000     47.677625   
max     9410.000000    4820.000000   2015.000000   2015.000000     47.777600   

               long  sqft_living15     sqft_lot15  
count  17384.000000   17384.000000   17384.000000  
mean    -122.213281    1985.994995   12776.380867  
std        0.140906     686.512835   27175.730523  
min     -122.519000     399.000000     651.000000  
25%     -122.328000    1490.000000    5100.000000  
50%     -122.229000    1840.000000    7620.000000  
75%     -122.125000    2360.000000   10065.250000  
max     -121.315000    6210.000000  871200.000000

In [6]:
data_train.dtypes

id                object
date              object
price            float64
bedrooms         float64
bathrooms        float64
sqft_living      float64
sqft_lot           int32
floors           float64
waterfront         int32
view               int32
condition          int32
grade              int32
sqft_above         int32
sqft_basement      int32
yr_built           int32
yr_renovated       int32
zipcode           object
lat              float64
long             float64
sqft_living15    float64
sqft_lot15       float64
dtype: object

## Is there any missing values

In [7]:
data_train.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [8]:
# Another way of checking if the values are missing. Checking if data is not NaN
# and then counting the False values

# data_train[data_train != np.nan].isnull().sum()

## Step 3

Create a function for creating a feature matrix and an output array for the labels.

In [9]:
def get_numpy_data(dataframe, features, output):
    """
    Create a function for creating a feature matrix and 
    an output array for the label variable.
    """
    
    # Add the constant term
    dataframe['constant'] = 1.
    
    # These features are wanted for the calculation
    features = ['constant'] + features
    
    # Check first that the dataframe is of type pandas
    if not isinstance(dataframe, pd.DataFrame):
        warnings.warn("dataframe must be pandas")
    else:          
        # Create feature matrix
        feature_matrix = dataframe[features].as_matrix()
        
        # Output array
        output_array = dataframe[output].as_matrix()
        
        return feature_matrix, output_array

## Step 4

Create a function that calculate the predicted values using the 
feature matrix and weigth array.

In [10]:
def predict_outcome(feature_matrix, weights):
    """
    Calculate the outcome valuse based on given weights and features.
    """
    predictions = np.dot(feature_matrix, weights)
    return predictions

## Step 5

Create a function that calculates the feature derivative, using the calculate error, i.e. (predictions - output)

RSS in matrix notation:

$$RSS(w) = (y-Hw)^T(y-Hw)$$

Gradient:

$$\nabla RSS(w) = -2H^T(y-Hw)$$

Where errors is: $(y-Hw)$


In [11]:
def feature_derivative(errors, feature_array):
    """
    Calculate the derivate of the regression cost function for ONE
    feature (i.e. one one column in the feature matrix).
    """
    # All inputs must be numpy arrays
    assert isinstance(errors, np.ndarray)
    assert isinstance(feature_array, np.ndarray)
      
    # Calculate the derivative of the cost function
    derivate = -2. * np.dot(feature_array, errors)
    
    return derivate

## Step 6

Create a gradient descent function. We will loop over the features individually for simplicity.

In [12]:
def regression_gradient_descent(feature_matrix, output_array, initial_weights, step_size, tol):
    """
    
    """
    converged = False
    nFeatures = feature_matrix.shape[-1] # Number of columns in the feature matrix
    weights = initial_weights
    
    # Counter that breaks the while loop if it does not converge
    counter = 0
    
    while not converged:
        # Compute the predictions based on weights
        predictions = predict_outcome(feature_matrix, weights)
         
        # Compute the errors between output and predictions
        # Important that the sign is correct
        errors = output_array - predictions
        
        # Initialize the gradient sum of squares before the for loop
        gradient_sum_squares = 0 
        
        # While not converged, update each weight individually
        for i, w in enumerate(weights):
            feature_col = feature_matrix[:, i]
            
            # Compute the derivative for weigth[i]
            derivative = feature_derivative(errors, feature_col)
                    
            gradient_sum_squares += derivative**2
            
            # Update weight
            weights[i] = weights[i] - (step_size * derivative)
            
        # Calculate the gradient magnitude
        gradient_magnitude = np.sqrt(gradient_sum_squares)
                
        if gradient_magnitude < tol:
            print "Algorithm has converged after %i iterations!" % counter
            converged = True
            return weights
        
        # While break
        counter += 1
        if counter == 100000:
            warnings.warn('while-loop-exit: counter reached: %i' % counter)
            break
        

In [13]:
# Simple check of the gradient descent funciton
x = np.array([0, 1, 2, 3, 4])
y = np.array([1, 3, 7, 13, 21])

# Setting up the x-array input to a feature matrix
def create_feature_matrix(x):
    # Initialize the ones matrix
    feature_matrix = np.ones((len(x), 2))
    # Add the values of the x vector
    feature_matrix[:, 1] = x
    
    return feature_matrix
    
# Set up the feature matrix from the 1-D x vector    
h = create_feature_matrix(x)

# Run the algorithm
weights = regression_gradient_descent(h, y, 
                                      initial_weights=np.array([0., 0.]),
                                      step_size=0.01, tol=1E-3)
weights # W

Algorithm has converged after 296 iterations!


array([-0.99969694,  4.99989369])

## Closed form solution test

$$\hat{w} = (H^TH)^{-1}H^Ty$$

In [14]:
tmp1 = np.linalg.inv(np.dot(h.T, h))
tmp2 = np.dot(tmp1, h.T)
weights = np.dot(tmp2, y)

weights # Looks good

array([-1.,  5.])

# 9. Quiz Question:

What is the value of the weight for sqft_living -- the second element of ‘simple_weights’ (rounded to 1 decimal place)?

### Setting up the parameters for my gradient descent function

In [15]:
# Feature selection
my_features = ['sqft_living',]
my_output = 'price'

# Extract to numpy matrix and array
feature_matrix, output_array = get_numpy_data(data_train, my_features, my_output)

step_size = 7E-12
tolerance = 2.5E7

# Check the dimensions of the data
print feature_matrix.shape, output_array.shape

(17384L, 2L) (17384L,)


### Running the gradient descent function

In [16]:
weights = regression_gradient_descent(feature_matrix, output_array, 
                                     initial_weights=np.array([-47000., 1.]),
                                     step_size=step_size, 
                                     tol=tolerance)

weights

Algorithm has converged after 11 iterations!


array([-46999.88716555,    281.91211918])

# 11. Quiz Question: 

What is the predicted price for the 1st house in the Test data set for model 1 (round to nearest dollar)?

In [17]:
features = ['sqft_living',]
output = 'price'

# Set up features and output
test_simple_feature_matrix, test_output = get_numpy_data(data_test, features, output)

# Predict the test data outcomes using the weights calculated above
predicted_test_output = predict_outcome(test_simple_feature_matrix, weights)

# Predicted value of the first house in the test dataset
predicted_test_output[0]

356134.44325500238

### 12. Now compute RSS on all test data for this model. Record the value and store it for later

In [18]:
def calc_rss(actual_output, predicted_output):
    """
    Calculate the rss between the actual and predicted output.
    """
    rss = np.sum((actual_output-predicted_output)**2)
    return rss

print calc_rss(test_output, predicted_test_output)

2.75400044902e+14


### 13. Now we will use the gradient descent to fit a model with more than 1 predictor variable (and an intercept). Use the following parameters:

In [19]:
features = ['sqft_living', 'sqft_living15']
output = 'price'

# Set up feature matrix and output array
feature_matrix, output_array = get_numpy_data(data_train, features, output)

initial_weights = np.array([-100000., 1., 1.])
step_size = 4E-12
tolerance = 1E9

weights = regression_gradient_descent(feature_matrix, output_array, 
                                      initial_weights, 
                                      step_size=step_size, 
                                      tol=tolerance)

# The calculated weights
print weights

Algorithm has converged after 273 iterations!
[ -9.99999688e+04   2.45072603e+02   6.52795267e+01]


### 15. Quiz Question: What is the predicted price for the 1st house in the TEST data set for model 2 (round to nearest dollar)?

In [20]:
test_feature_matrix, test_outcome = get_numpy_data(data_test, features, output)

predicted_test_output = predict_outcome(test_feature_matrix, weights)

predicted_test_output[0]

366651.41162949387

In [21]:
print calc_rss(test_outcome, predicted_test_output)

2.7026344363e+14


Which estimate was closer to the true price for the 1st house on the TEST data set, model 1 or model 2?

In [22]:
price_test_house = data_test.price[0]
price_test_house

310000.0

We see that model 1 predicts a closer value for the first house. However, the overall RSS is best for model 2, meaning that the more detailed model, taking into account both sqft_living and sqft_living15 gives a better overall result.